<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="g350ch2x.phu~" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\TrafficLedger.Common.Core\TrafficLedger.Common.Core.csproj" />
    <ProjectReference Include="..\TrafficLedger.Common.Repositories.Contracts\TrafficLedger.Common.Repositories.Contracts.csproj" />
    <ProjectReference Include="..\TrafficLedger.Common.Services\TrafficLedger.Common.Services.csproj" />
    <ProjectReference Include="..\TrafficLedger.Context.Contracts\TrafficLedger.Context.Contracts.csproj" />
    <ProjectReference Include="..\TrafficLedger.Entities\TrafficLedger.Entities.csproj" />
    <ProjectReference Include="..\TrafficLedger.Repositories.Contracts\TrafficLedger.Repositories.Contracts.csproj" />
    <ProjectReference Include="..\TrafficLedger.Services.Contracts\TrafficLedger.Services.Contracts.csproj" />
  </ItemGroup>

</Project>
