<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.12" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\TrafficLedger.Common.Repositories.Contracts\TrafficLedger.Common.Repositories.Contracts.csproj" />
    <ProjectReference Include="..\TrafficLedger.Context.Contracts\TrafficLedger.Context.Contracts.csproj" />
    <ProjectReference Include="..\TrafficLedger.Entities.Contracts\TrafficLedger.Entities.Contracts.csproj" />
    <ProjectReference Include="..\TrafficLedger.Entities\TrafficLedger.Entities.csproj" />
  </ItemGroup>

</Project>
